CREATE PROCEDURE Proc_GetLatestOrder
	@CustomerId INT
AS
BEGIN
	DECLARE @LatestOrder TABLE (
		FirstName NVARCHAR(50), 
		LastName NVARCHAR(50), 
		DeliveryAddress NVARCHAR(255),
		OrderId INT,
		OrderDate Date,
		DeliveryExpected Date,
		ContainsGift Bit);
	INSERT INTO @LatestOrder
	SELECT FIRSTNAME, LASTNAME, CONCAT(HOUSENO,', ',STREET,', ',TOWN,', ',POSTCODE) AS DELIVERYADDRESS, ORDERID, ORDERDATE, DELIVERYEXPECTED, CONTAINSGIFT FROM CUSTOMERS C
	INNER JOIN ORDERS O ON O.CUSTOMERID = C.CUSTOMERID
	WHERE C.CUSTOMERID = @CustomerId AND O.ORDERDATE = (SELECT MAX(ORDERDATE) FROM ORDERS WHERE CUSTOMERID = @CustomerId)

	SELECT * FROM @LatestOrder

	SELECT CASE L.ContainsGift
		 WHEN 1 THEN 'Gift'
		 ELSE P.PRODUCTNAME
	 END
	 AS PRODUCTNAME,
	O.QUANTITY, O.PRICE FROM ORDERITEMS O
	INNER JOIN PRODUCTS P ON P.PRODUCTID = O.PRODUCTID
	INNER JOIN @LatestOrder L ON L.OrderId = O.ORDERID
END